### ISSUE TITLE
Make new Copper release.

### ISSUE THREAD

**Issue by schwerdf** [melt-umn/copper#11]
With the addition of Kevin's new parser compilation pipelines and other features to Copper, a version number bump is in order.

Issues #8 and #10 should be resolved first, so I am assigning to myself to start.

Once these issues are closed, the release candidate should be put through some more aggressive testing, since many of the changes since Copper 0.7.2 could potentially destabilize the default pipeline. Theoretically, all changes in behavior would be outside the main pipeline, so it should suffice to swap it into Silver in the place of 0.7.2 and see if anything breaks.

**Comment by tedinski** [comment]
I believe Jenkins is tracking the develop branch, and doing integration testing with Silver (at least building itself) automatically.

**Comment by schwerdf** [comment]
How would the installation of Jenkins signal a failure, if I broke something with a commit?

**Comment by tedinski** [comment]
Right now you'd have to be on the CS network (do you still have VPN access? Otherwise SSH?) to get to coldpress.cs.umn.edu:8080

I believe there's a job called `copper` and `copper-integration` that tries to rebuild Silver with a new Copper jar. I think it's on the TODO list to upgrade how we do Jenkins builds to signal build success/failure directly on Github. (This will eventually involve a pull request adding a `Jenkinsfile` to this repo.)
