### ISSUE TITLE
Better management of empty productions

### ISSUE THREAD

**Issue by massimo-zaniboni** [melt-umn/copper#3]
Hi, I'm asking a feedback for a new feature/behavior that I would add to Copper, if I'm able. I'm not an expert of LALR parsers, so you can inform me if this is a stupid idea.

In my grammar I have a lot of productions with empty rules like this:

nonterminal Stmt;
concrete productions r::Stmt 
  | 'if' c::Condition 'then' s::Stmt else::OptionalElse { }
  | ... other cases ...

nonterminal OptionalElse;
concrete productions r::OptionalElse 
  | 'else' s::Stmt { }
  | { }

With two or more consecutive empty rules, the parser signal a shift/reduce conflict, because it does not know if the empty string is assigned to the inner or outer `if`.

In all my rules, I want that the meaning of a production with an explicit empty rule (but not of general shift/reduce conflictsf) is "if there is no match, match the empty rule, and then continue with the parsing of the input string from left to right."

I suspect that this feature is implementable, because the parser can tell if a production is matching or not, without incurring in a backtracking process. It is always a LALR(1) parser, and the test is only on a production, so the lookahead suffices.

I like this approach because it makes a LALR parser (IMHO) more user-friendly, without loosing the benefit of static checking of grammars of LALR parsers, respect top-down parsers. In particular this behavior allows to manage productions with nested forms like `A?`, `A*`, `A+`, because they are all reducible to productions with a default empty rule. 

Can you inform me, if I'm wrong/naive in some point of my discourse, because I'm not expert of the field of parsers, and before working on it, it is better for me receiving some feedback/advice.

Thanks in any case, and many thanks for the good work with Copper.
Massimo

**Comment by schwerdf** [comment]
Copper already has a way of resolving the dangling-else ambiguity, as it is called. The `%prec` attribute on productions, which you can read about on pp.17-18 of Copper's user manual, lets you assign a precedence to an empty production such as `OptionalElse ::= `, which can be compared with the precedence of the `else` terminal to resolve the shift-reduce conflict.

I gather from the syntax in your examples that you are using Copper through Silver. This same functionality can be accessed through Silver using the `operator` production modifier:

    concrete production OptionalElse_c
    top::OptionalElse ::=
    operator = SomeTerminal
    {}

**Comment by tedinski** [comment]
I could be mistaken because it's been awhile, but I believe in this particular situation you'd want to set the operator to 'else' on the empty production and give the 'else' terminal a right(?)-association.

I'm a bit fuzzy on this, but I believe lower precedence (or same terminal but right association) means "always shift" and the other way around means "always reduce."  This is an area where LR tradition has given us an abstraction that's very good at some shift/reduce errors (like actual operators) and is rather counter-intuitive when resolving other shift/reduce errors.

I'm going to make a note of what you suggest is a common pattern in melt-umn/silver#71.

**Comment by massimo-zaniboni** [comment]
In reality up to date there is no a true answer, (for my limitations in expressing the question), but a lot of useful advises! Many thanks. 

A copy and paste of one of my grammar rule:

````
    -- | A type reference/usage.
   nonterminal Type with ast<dok:Type>;
  concrete productions r::Type
      | isRoot::IsRootTypeRef t::TypeRef ts::TypeSequence
      { r.ast = dok:typeExpr([dok:subType(isRoot.ast, t.ast)] ++ ts.ast, ts.typeCardinality); 
      }

    nonterminal IsRootTypeRef with ast<Boolean>;
    concrete productions r::IsRootTypeRef
      | '/'
      { r.ast = true;
      }
      |
      { r.ast = false;
      }
````

so `IsRootTypeRef` is like a `IsRootTypeRef?` because it is an optional token: if there is the "/" string it is a root type, if there is no the "/", it is not a root type.

Full disclosure: I'm bootstrapping a programming language based on attribute grammars paradigm (so a replacement of Silver) using Silver as implementation language, in the first pass of the bootstrapping process. My language allows also the definitions of grammars. So I'm both interested to a simple/elegant definition of the grammar of my language, but in reality mainly to a nice grammar language to use inside my language, so exposed to users of the language.

I have more experience with top-down parsers, like Parsec in Haskell. In case of Parsec I can create complex grammar rules, combining simple rules. So something like described in melt-umn/silver#71.

But using top-down parsers, I have no compile-time checking of the grammar, like in case of Copper. So I have no problems reducing a lot of the expressive power of top-down combinatoric parsers, if in exchange I inherit static checking of the grammar. 

For expression-like productions, with operators, for sure the precedence and associativity of LALR grammars is superior to top-down parsers. So in this case I have the best: both static checking and expressive power. So many thanks for the remark.

But for expressing rules like `A*, A+, A?`, LALR grammars are not very good, and in this context, the usage of precedence is IMHO more a trick than an elegant solution.

So probably I will try to use my suggested management of `empty string`, because I can then express a lot of common rules, involving `A?` and derived patterns, without the need of fancy rewriting of the grammar, and the semantic is clear. I will use precedences only for operators in math-like expressions.

Parametric grammar rules like described in umn/silver#71 are another pass for creating a grammar easy to specify like top-down combinatoric parsers, but I wll evaluate it after implementing this task.

By the way I selected Copper because it informs the lexer about the allowed tokens, and it reduces the conflicts in the specification of the grammar/lexer, expecially in case of many DSL programming languages in the same file. Another pass towards a compile-time checkable grammar, but easy to specify.

Sorry for this long message. I hope it is more clear.

**Comment by tedinski** [comment]
> But for expressing rules like A*, A+, A?, LALR grammars are not very good, and in this context, the usage of precedence is IMHO more a trick than an elegant solution.

"Elegant" perhaps not, but that's what I was getting at with this remark:

> This is an area where LR tradition has given us an abstraction that's very good at some shift/reduce errors (like actual operators) and is rather counter-intuitive when resolving other shift/reduce errors.

Operator precedence is a fully general solution to resolving shift/reduce conflicts in a simplistic way (that is, choosing "always shift" or "always reduce" as the resolution.)

A shift/reduce conflict involves a terminal and a production. The production gets mapped to a terminal (either inferred as the last terminal in the production signature, or specified manually as we suggest above for empty productions), and then you can compare these two terminals (via precedence and association) to decide which one "wins."

So I think the end result is that it does do exactly what you want, it's just presented in a way that makes it seem like a very weird solution when the shift/reduce conflict is not actually involving operators, and thus "operator precedence" doesn't seem like it should be applicable. But, that's the way LR parsers do it... at least so far.

(BTW, with your latest example, is there actually any conflict? Unless `TypeRef` can start with `'/'`, it should just work. And if it can start with `'/'`, perhaps consider analyzing the subtree to discover this, instead of trying to spot the starting `'/'` with the parser? At any rate, we are perhaps straying into general LR parser design rather than something specific to copper here... Is there a good venue for asking LR grammar questions? Stackoverflow? I haven't used it, so I'm not sure. A quick glance suggest there are 'parsing' and 'grammar' tags. Perhaps I ought to get an account there... But I digress.)

**Comment by schwerdf** [comment]
It looks like the Copper-related aspects of the question have been answered.

As to the general aspects: Indiscriminate application of shift-reduce conflict resolution in LALR(1) grammars quite often leads to unexpected, undesired, and extremely confusing results. If you try to automate EBNF-to-BNF conversion by those means, you will be opening up a real can of worms.

**Comment by massimo-zaniboni** [comment]
Many thanks for the patience. :-)

BTW I tried to subscribe to the mailing list at https://wwws.cs.umn.edu/mm-cs/listinfo/melt-help, before opening this "discussion" issue, but I never received a confirmation email (I checked also the SPAM, and I tried with two different email address). Now I tried subscribing sending an email to melt-help-join@cs.umn.edu (as described in mailman manual), and it seems ok (after approvation). Only as feedback/information.

**Comment by ericvanwyk** [comment]
Hi Massimo - thanks for your interest in Copper.  I just approved your subscription for joining the melt-help mail list. It only just arrived in my in box, so I'm not sure what the delay was.

I agree with August that this idea could open an interesting can of worms.  We've wondered about extending Copper to support EBNF but the tricky part is what to do with semantic actions since using a * to indicate zero-or-more is useful in many contexts, these contexts will like want different functions for constructing the list-like tree of recognized constructs.

May I ask what sort of things you are using Copper for?  Are you by chance working with Walter Cazzola?

Cheers,
Eric

**Comment by massimo-zaniboni** [comment]
Hi, I studied better LALR and Copper, changed the grammars, and I completely agree with all the remarks/suggestions I received in this issue. Next pass: I will try to document them in some way, and I will send a pull request.  

> May I ask what sort of things you are using Copper for?

I will answer on the mailing-list: so I test it.

Many thanks,
Massimo
